### ISSUE TITLE
Improve error reporting options for metacello builds

### ISSUE THREAD

**Issue by macta** [ba-st/docker-pharo#7]
When following a recent blog-post for using Docker to run Pharo (https://thepharo.dev/2021/02/24/running-pharo-9-in-docker/) - I tried to load my project in a similar way and had a similar RUN command e.g.:

RUN ./pharo Pharo.image eval --save "Metacello new \
baseline:'MyApp'; \
repository: 'gitlab://me/MyApp/src'; \
onConflict: [ :ex | ex useLoaded ]; \
load"

However my repository "MyApp" was a private repo, and this Docker image ( or Pharo) doesn't cope well with this - as the output to the terminal when running docker build just seems to hang - e.g. I was seeing:

```
$ docker build -t pharo/myapp:latest .
[+] Building 684.3s (5/6)                                                                                                                                       
 => [internal] load build definition from Dockerfile                                                                                                       0.0s
 => => transferring dockerfile: 382B                                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                            0.0s
 => [internal] load metadata for docker.io/basmalltalk/pharo:8.0-image                                                                                     0.0s
 => [1/3] FROM docker.io/basmalltalk/pharo:8.0-image     
<hangs here until you press CTRL-C>                                                                                                  
 => CANCELED [2/3] RUN ./pharo Pharo.image eval --save "Metacello new baseline:'MyApp'; repository: 'gitlab://me/MyApp'; onConflict: [ :ex | ex   684.2s
 ```
This had me stumped and its made particularly mysterious because the Docker output (even with --progress=plain) shows nothing - it just echo's the VM info text and then stops and hangs. 

I am guessing that there is a credentials error/system prompter sitting waiting for user input. I think there should be a way to disable this behaviour somehow - but at the very least it should write something out to stderr so that you know something has happened?

Not sure if we can propose something extra for Pharo to get a credentials error to log out to the console - or if we can somehow include some helpful modification in the image to do this?

Possibly my solution could be documented as a help text here?

Luckily there is an easy fix (for anyone wanting to load their own private project) - rather than using the "eval" command, use the "st" command and specify a load.st script. In this script specify some IceCredentialStore details eg:

IceCredentialStore current
	storeCredential: (IceTokenCredentials new
		username: 'email@mail.com';
		token: 'xxxxxxxxxxxxxxx';
		yourself) 
		forHostname: 'gitlab.com'.

Metacello new
    baseline: 'myapp';
    repository: 'gitlab://me/repo'';
	onConflict: [ :ex | ex useLoaded ];
	onUpgradeUseLoaded;
	onWarningLog;
    load.

I also added some extra logging to my load.st - eg.

| logger |
logger := Stdio stderr.

logger crlf; nextPutAll: 'Starting Load Script...'.

**Comment by serpi90** [comment]
https://gitlab.com/ba-st/deployment/docker-pharo/-/issues/1
This was raised in a mirror repository, referencing here just in case.
